### ISSUE TITLE
Passing 0 as slide name fails

### ISSUE THREAD

**Issue by donaldwasserman** [crhayes/ember-slides#1]
If you pass 0 to the name of the slide (like when using an array index as slide names), active slide can't be set.

**Comment by crhayes** [comment]
@donaldwasserman Tagged a new version `0.3`. I added a changelog that outlines the changes: https://github.com/crhayes/ember-slides/blob/master/CHANGELOG.md

Let me know if you have any issues running this against `3.2`. I installed `3.2` locally and it appears to be working.

I will be upgrading this addon to `3.2` in the near future when the `ember-cli-update` addon supports it.
